create table if not exists public.group_module_config (
  id bigint generated by default as identity primary key,
  group_id bigint references public.groups(id) on delete cascade,
  athlete_id bigint references public.athletes(id) on delete cascade,
  module text not null check (module in ('wellness', 'diet')),
  enabled boolean not null default true,
  pre_params text[] not null default '{}',
  post_params text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint group_module_config_owner_check check (
    (group_id is not null and athlete_id is null)
    or (group_id is null and athlete_id is not null)
  )
);

create unique index if not exists group_module_config_group_module_key
  on public.group_module_config(group_id, module);

create unique index if not exists group_module_config_athlete_module_key
  on public.group_module_config(athlete_id, module);

alter table public.group_module_config enable row level security;

drop policy if exists "Coach can manage module config" on public.group_module_config;
create policy "Coach can manage module config"
  on public.group_module_config for all
  to authenticated
  using ((select auth.email()) = 'cheerlevelup@gmail.com')
  with check ((select auth.email()) = 'cheerlevelup@gmail.com');

drop policy if exists "Athlete can read own module config" on public.group_module_config;
create policy "Athlete can read own module config"
  on public.group_module_config for select
  to authenticated
  using (
    exists (
      select 1
      from public.athletes a
      where a.user_id = auth.uid()
        and (
          public.group_module_config.athlete_id = a.id
          or public.group_module_config.group_id = a.group_id
        )
    )
  );
