-- Katalog testów sprawnościowych definiowanych przez trenera (nazwa, jednostka,
-- pełny opis protokołu: PP/wykonanie/PK/pomiar/cel) — zastępuje sztywną listę
-- typów testów w benchmark_tests. Migracja jest samowystarczalna: jeśli
-- benchmark_tests jeszcze nie istnieje (poprzednia migracja niewklejona),
-- tworzy go od razu z nowym modelem; jeśli istnieje z kolumną test_type,
-- migruje istniejące wyniki do nowego katalogu zanim ją usunie.

create table if not exists public.test_catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  unit text not null default '',
  general_desc text,
  starting_position text,
  execution text,
  end_position text,
  measurement text,
  goal text,
  is_archived boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.test_catalog enable row level security;

drop policy if exists "Coach can manage test catalog" on public.test_catalog;
create policy "Coach can manage test catalog"
  on public.test_catalog for all
  to authenticated
  using ((select auth.email()) = 'cheerlevelup@gmail.com')
  with check ((select auth.email()) = 'cheerlevelup@gmail.com');

-- Domyślne wpisy odpowiadające dotychczasowym sztywnym typom testów (tylko
-- przy pustym katalogu — nie dubluje przy ponownym uruchomieniu).
insert into public.test_catalog (name, unit, sort_order)
select v.name, v.unit, v.sort_order
from (values
  ('Broad jump (obunóż)', 'cm', 1),
  ('Broad jump (prawa)', 'cm', 2),
  ('Broad jump (lewa)', 'cm', 3),
  ('Chin-up', 'sek', 4),
  ('Push-up', 'powt.', 5)
) as v(name, unit, sort_order)
where not exists (select 1 from public.test_catalog);

-- benchmark_tests: tworzymy od zera z nowym modelem, jeśli jeszcze nie istnieje.
create table if not exists public.benchmark_tests (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  test_catalog_id bigint references public.test_catalog(id) on delete set null,
  value numeric,
  test_date date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists benchmark_tests_athlete_id_idx on public.benchmark_tests(athlete_id);

alter table public.benchmark_tests enable row level security;

drop policy if exists "Coach can manage benchmark tests" on public.benchmark_tests;
create policy "Coach can manage benchmark tests"
  on public.benchmark_tests for all
  to authenticated
  using ((select auth.email()) = 'cheerlevelup@gmail.com')
  with check ((select auth.email()) = 'cheerlevelup@gmail.com');

-- Jeśli benchmark_tests istniał już wcześniej ze starą kolumną test_type,
-- dopisz test_catalog_id, przemapuj dane po nazwie starego typu, dopiero
-- potem usuń test_type.
alter table public.benchmark_tests add column if not exists test_catalog_id bigint references public.test_catalog(id) on delete set null;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'benchmark_tests' and column_name = 'test_type'
  ) then
    update public.benchmark_tests bt
    set test_catalog_id = tc.id
    from public.test_catalog tc
    where bt.test_catalog_id is null and (
      (bt.test_type = 'broad_jump_both' and tc.name = 'Broad jump (obunóż)') or
      (bt.test_type = 'broad_jump_right' and tc.name = 'Broad jump (prawa)') or
      (bt.test_type = 'broad_jump_left' and tc.name = 'Broad jump (lewa)') or
      (bt.test_type = 'chin_up' and tc.name = 'Chin-up') or
      (bt.test_type = 'push_up' and tc.name = 'Push-up')
    );

    alter table public.benchmark_tests drop column test_type;
  end if;
end $$;
