-- Profil trenera: lista własnych "funkcji" (np. Trener przygotowania
-- motorycznego) i przypisanie ich do konkretnych grup. Na razie luźna
-- ewidencja bez większych zobowiązań w reszcie aplikacji — trener sam
-- wpisuje sobie funkcje i wybiera, w której grupie pełni jaką.

create table if not exists public.coach_functions (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.coach_functions enable row level security;

drop policy if exists "Coach can manage coach functions" on public.coach_functions;
create policy "Coach can manage coach functions"
  on public.coach_functions for all
  to authenticated
  using ((select auth.email()) = 'cheerlevelup@gmail.com')
  with check ((select auth.email()) = 'cheerlevelup@gmail.com');

create table if not exists public.coach_group_roles (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.groups(id) on delete cascade,
  function_id bigint not null references public.coach_functions(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists coach_group_roles_group_id_idx on public.coach_group_roles(group_id);

alter table public.coach_group_roles enable row level security;

drop policy if exists "Coach can manage coach group roles" on public.coach_group_roles;
create policy "Coach can manage coach group roles"
  on public.coach_group_roles for all
  to authenticated
  using ((select auth.email()) = 'cheerlevelup@gmail.com')
  with check ((select auth.email()) = 'cheerlevelup@gmail.com');
