-- Rozszerzenie profilu zawodniczki (telefon/wzrost/waga/notatki) + nowe tabele
-- kontuzji i testów sprawnościowych, na potrzeby rozwijanej karty zawodniczki
-- w zakładce "Zawodniczki".

alter table public.athletes add column if not exists phone text;
alter table public.athletes add column if not exists height_cm numeric;
alter table public.athletes add column if not exists weight_kg numeric;
alter table public.athletes add column if not exists notes text;

create table if not exists public.injuries (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  body_part text,
  status text not null default 'active' check (status in ('active', 'in_treatment', 'healed', 'chronic')),
  date_occurred date,
  date_resolved date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists injuries_athlete_id_idx on public.injuries(athlete_id);

alter table public.injuries enable row level security;

drop policy if exists "Coach can manage injuries" on public.injuries;
create policy "Coach can manage injuries"
  on public.injuries for all
  to authenticated
  using ((select auth.email()) = 'cheerlevelup@gmail.com')
  with check ((select auth.email()) = 'cheerlevelup@gmail.com');

create table if not exists public.benchmark_tests (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null references public.athletes(id) on delete cascade,
  test_type text not null check (test_type in (
    'broad_jump_both', 'broad_jump_right', 'broad_jump_left', 'chin_up', 'push_up'
  )),
  value numeric,
  test_date date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists benchmark_tests_athlete_id_idx on public.benchmark_tests(athlete_id);

alter table public.benchmark_tests enable row level security;

drop policy if exists "Coach can manage benchmark tests" on public.benchmark_tests;
create policy "Coach can manage benchmark tests"
  on public.benchmark_tests for all
  to authenticated
  using ((select auth.email()) = 'cheerlevelup@gmail.com')
  with check ((select auth.email()) = 'cheerlevelup@gmail.com');
