-- ============================================================
-- GRUPY ZORGANIZOWANE (np. Ultra) — trener prowadzi całą grupę
-- Uruchom w Supabase SQL Editor
-- ============================================================

-- 1. Rodzaj grupy: 'self' (samodzielna) lub 'managed' (zorganizowana)
ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS group_type text NOT NULL DEFAULT 'self'
  CHECK (group_type IN ('self', 'managed'));

-- Ultra staje się grupą zorganizowaną
UPDATE public.groups SET group_type = 'managed' WHERE lower(name) = 'ultra';

-- Trener może tworzyć nowe grupy
DROP POLICY IF EXISTS "coach_insert_groups" ON public.groups;
CREATE POLICY "coach_insert_groups" ON public.groups
  FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.email()) = 'cheerlevelup@gmail.com');

-- 2. Treningi grupowe (jeden trening = jedna data dla całej grupy)
CREATE TABLE IF NOT EXISTS public.group_trainings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  training_date date NOT NULL DEFAULT current_date,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (group_id, training_date)
);

-- 3. Ćwiczenia w treningu grupowym (kolumny tabeli)
CREATE TABLE IF NOT EXISTS public.group_training_exercises (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  training_id bigint NOT NULL REFERENCES public.group_trainings(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  exercise_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. Wpisy: zawodniczka × ćwiczenie (serie jako JSON + ból + komentarz)
CREATE TABLE IF NOT EXISTS public.group_training_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  training_id bigint NOT NULL REFERENCES public.group_trainings(id) ON DELETE CASCADE,
  exercise_id bigint NOT NULL REFERENCES public.group_training_exercises(id) ON DELETE CASCADE,
  athlete_id bigint NOT NULL REFERENCES public.athletes(id) ON DELETE CASCADE,
  -- sets: [{ "reps": "8", "tempo": "3010", "weight": "20" }, ...]
  sets jsonb NOT NULL DEFAULT '[]'::jsonb,
  pain_vas int CHECK (pain_vas BETWEEN 0 AND 10),
  pain_comment text,
  comment text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (exercise_id, athlete_id)
);

-- RLS: tylko trener
ALTER TABLE public.group_trainings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_training_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_training_entries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "coach_manage_group_trainings" ON public.group_trainings;
CREATE POLICY "coach_manage_group_trainings" ON public.group_trainings
  FOR ALL TO authenticated
  USING ((SELECT auth.email()) = 'cheerlevelup@gmail.com')
  WITH CHECK ((SELECT auth.email()) = 'cheerlevelup@gmail.com');

DROP POLICY IF EXISTS "coach_manage_group_training_exercises" ON public.group_training_exercises;
CREATE POLICY "coach_manage_group_training_exercises" ON public.group_training_exercises
  FOR ALL TO authenticated
  USING ((SELECT auth.email()) = 'cheerlevelup@gmail.com')
  WITH CHECK ((SELECT auth.email()) = 'cheerlevelup@gmail.com');

DROP POLICY IF EXISTS "coach_manage_group_training_entries" ON public.group_training_entries;
CREATE POLICY "coach_manage_group_training_entries" ON public.group_training_entries
  FOR ALL TO authenticated
  USING ((SELECT auth.email()) = 'cheerlevelup@gmail.com')
  WITH CHECK ((SELECT auth.email()) = 'cheerlevelup@gmail.com');

-- 5. Powiązanie gotowości i feedbacku z treningiem grupowym
ALTER TABLE public.wellness_logs
  ADD COLUMN IF NOT EXISTS group_training_id bigint REFERENCES public.group_trainings(id) ON DELETE SET NULL;

ALTER TABLE public.post_session_feedback
  ADD COLUMN IF NOT EXISTS group_training_id bigint REFERENCES public.group_trainings(id) ON DELETE SET NULL;

-- 6. Feedback z kiosku nie ma sesji zawodniczki — kolumny sesji muszą dopuszczać NULL
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'post_session_feedback' AND column_name = 'session_id') THEN
    ALTER TABLE public.post_session_feedback ALTER COLUMN session_id DROP NOT NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'post_session_feedback' AND column_name = 'workout_session_id') THEN
    ALTER TABLE public.post_session_feedback ALTER COLUMN workout_session_id DROP NOT NULL;
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'wellness_logs' AND column_name = 'session_id') THEN
    ALTER TABLE public.wellness_logs ALTER COLUMN session_id DROP NOT NULL;
  END IF;
END $$;

-- 7. Trener może zapisywać gotowość i feedback w imieniu zawodniczek (tryb kiosku)
DROP POLICY IF EXISTS "coach_manage_wellness" ON public.wellness_logs;
CREATE POLICY "coach_manage_wellness" ON public.wellness_logs
  FOR ALL TO authenticated
  USING ((SELECT auth.email()) = 'cheerlevelup@gmail.com')
  WITH CHECK ((SELECT auth.email()) = 'cheerlevelup@gmail.com');

DROP POLICY IF EXISTS "coach_manage_feedback" ON public.post_session_feedback;
CREATE POLICY "coach_manage_feedback" ON public.post_session_feedback
  FOR ALL TO authenticated
  USING ((SELECT auth.email()) = 'cheerlevelup@gmail.com')
  WITH CHECK ((SELECT auth.email()) = 'cheerlevelup@gmail.com');
